c_compiler:                    # [win]
  - vs2008                     # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]
cxx_compiler:                  # [win]
  - vs2008                     # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]
CONDA_BUILD_SYSROOT:           # [osx]
  - /opt/MacOSX10.9.sdk        # [osx]
VERBOSE_AT:
  - V=1
VERBOSE_CM:
  - VERBOSE=1
macos_min_version:              # [osx]
  - 10.9                        # [osx]
macos_machine:                  # [osx]
  - x86_64-apple-darwin13.4.0   # [osx]
MACOSX_DEPLOYMENT_TARGET:       # [osx]
  - 10.9                        # [osx]
python:
  - 2.7
  - 3.5
  - 3.6
# This differs from target_platform in that it determines what subdir the compiler
#    will target, not what subdir the compiler package will be itself.
#    For example, we need a win-64 vs2008_win-32 package, so that we compile win-32
#    code on win-64 miniconda.
cross_compiler_target_platform:
  - win-32                     # [win]
  - win-64                     # [win]
target_platform:
  - win-64                     # [win]
  - win-32                     # [win]
vc:
  - 9                          # [win]
  - 14                         # [win]
  - 14                         # [win]
zip_keys:
  -                             # [win]
    - vc                        # [win]
    - c_compiler                # [win]
    - cxx_compiler              # [win]
    - python                    # [win]
  -                             # [osx]
    - macos_min_version         # [osx]
    - macos_machine             # [osx]
    - MACOSX_DEPLOYMENT_TARGET  # [osx]
    - CONDA_BUILD_SYSROOT       # [osx]
