{% set version = "3.10.4" %}

package:
  name: geos
  version: {{ version }}

source:
  url: https://download.osgeo.org/geos/geos-{{ version }}.tar.bz2
  sha256: d6fc11bcfd265cbf2714199174e4c3392d657551e5fd84c74c07c863b29357e3
  patches:
    - patches/0001-unconditional-geos-pc.patch

build:
  number: 0

requirements:
  build:
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}

test:
  commands:
    - geos-config --version  # [not win]
    - geosop --help
    - geosop -a "POINT (0 0)" buffer 1

about:
  home: https://libgeos.org/
  license: LGPL-2.1-only
  license_file: COPYING
  summary: Geometry Engine, Open Source
  description: |
    GEOS is a C++ library for performing operations on two-dimensional vector
    geometries. It is primarily a port of the JTS Topology Suite Java library.
    It provides many of the algorithms used by PostGIS, the Shapely package
    for Python, the sf package for R, and others.
  doc_url: https://libgeos.org/
  dev_url: https://github.com/libgeos/geos

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - gillins
    - msarahan
    - mwtoews
    - xylar
