# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "GiVZtIHPc0hjy8rk+czPaquRhqRkm1er8ubeVXI3/o23jz+JfedM54d8sOgdCJ7yGm6o5atlJ5XnxkViLQL7Gv/LBJPQxXy5YUjW8WxBFqhDJdjjX9lTV8guQqTpp5eV4qz2lhCoMBibUoOdkmkInF3HieWnJTDg7d9FIPvy4J05pVnlDhKvhMhAtMkqysBAvWcwZdCHP6sQBZ250KRZcKD3WudP1oTZZwRB1jXrB6qH3b7/Nz7YSXK9Sv7tawYZmb+Cam5YLr79+VVae2yWWaI0zwDpyR8rmOjiGQxJENXuNBTEP5W9wYQtbE5sha9eQ4QObcBfkm5b3NVR4wAGr1Z1ddHlXyFEU/Itc7HW5rZsyYloD7XQtDJdOrdg3u+h92weYwUJWXOBB71FrKYO1VcD640e33Uw3ehhN563UTU9aD933p3GZJKwe2xYwRUKp1VR2zKf6QCpWeZRNU9OXAGVFEdM/orIO1cBCG/BwF+iFEhvxtr2/V1gvwnzrRiMrsc/6neLJuM7tBBac6sVs8vGc4nK7VnNKbyLNZj9eQy8V4YOPlE+EsbI1RzNEgduywdP3A8H8bYWE9/3siaQkt1yhWV71gMVxmK7Ug5jB47agLU/er9vSpbjirgTgIqhgqVsjC5czQ/hBTWVpqQc/GOryChRY9XBz8ElpjrWil4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup
      conda install conda-build=3 --yes
      conda config --add channels c3i_test --force
      conda info

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
