# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "RCQW91N9R13wGYLa/eGic6p8qTLfmXmfLO4Zftxgkh056YY8dYXHdRZVKS3rL+8y2v/asT53CCFYXG/49S6sFsC0M294K7PDsgGTz1xBshF2ES6bpQwAUe1kJJcV1AznOT2yrhxaZX8bi/Ibrq2at5Bycv1bPpkABtvFld+JAwEt/xDloI6Jnglf2btvlGQptunEe2vnGyljT2EmkCrRFi+OyU9c1xS5hvqv4PMbZ92kaO00wB0BQOBXtuf1dItp9y4dCr/fjMMfYleJDL26kD+xwHcxwy7GXrMITwZz74J+2TT8KJEubnsme594+P7WeeUixTpU0aosPVjSWnYkv8Z9EORP1SUdUo3Y5buJWDLLs8fOPIzMKEwkQDMsvUateiHVhS/P2/QDd8NxEpUcL+OEl4K2DI6FndgO4qwNlSfzzZ06ExZN/wXjejh10lumf7To23dg4x+u7WQ7QPXMvZRiGpoVw6yon4tN7bbG2RQYmXJehJDR2Z9qVdeUMYCxQd3FAAeeSU6BeZLcSxiuCEuhZJaxJ2+8aZBBc7P2u0/ONk0Kb/nYSySUVF7SoM3g/RRHs5ws7Ox4MvkI50Yv8GmYRfTfjjOm9S+5jL9EJcE2dRxusGwmrmMJUR7dx92n5pyHomHgV23M3ZSAcvr/bFZRTYPpZ1Xtx8EnmjLADM8="

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=condaforge/linux-anvil-ppc64le
      os: linux
      arch: ppc64le

script:
  - export CI=travis
  - export GIT_BRANCH="$TRAVIS_BRANCH"


  - if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi